gencode_gene:
  adapter:
    module: biocypher_metta.adapters.hsa.hsa.gencode_gene_adapter
    cls: GencodeGeneAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/gencode/Drosophila_melanogaster.BDGP6.46.59.gtf.gz
      dmel_gene_alias_file_path: ./aux_files/Drosophila_melanogaster.gene_info.gz
      hsa_filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz
      hsa_gene_alias_file_path: ./aux_files/Homo_sapiens.gene_info.gz

  outdir: gencode/gene
  nodes: True
  edges: False


gencode_transcripts:
  adapter:
    module: biocypher_metta.adapters.hsa.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/gencode/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz
      type: transcript
      label: transcript

  outdir: gencode/transcript
  nodes: True
  edges: False


gencode_exon:
  adapter:
    module: biocypher_metta.adapters.hsa.gencode_exon_adapter
    cls: GencodeExonAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/gencode/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz

  outdir: gencode/exon
  nodes: True
  edges: False

transcribed_to:
  adapter:
    module: biocypher_metta.adapters.hsa.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/gencode/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz
      type: transcribed to
      label: transcribed_to

  outdir: gencode
  nodes: False
  edges: True

transcribed_from:
  adapter:
    module: biocypher_metta.adapters.hsa.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/gencode/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz
      type: transcribed from
      label: transcribed_from

  outdir: gencode
  nodes: False
  edges: True


uniprotkb_sprot:
  adapter:
    module: biocypher_metta.adapters.hsa.uniprot_protein_adapter
    cls: UniprotProteinAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/uniprot/uniprot_sprot_invertebrates_DMEL.dat.gz
      hsa_filepath: /mnt/hdd_2/abdu/biocypher_data/uniprot/uniprot_sprot_human.dat.gz
  outdir: uniprot
  nodes: True
  edges: False

uniprotkb_sprot_translates_to:
  adapter:
    module: biocypher_metta.adapters.hsa.uniprot_adapter
    cls: UniprotAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/uniprot/uniprot_sprot_invertebrates_DMEL.dat.gz
      hsa_filepath: /mnt/hdd_2/abdu/biocypher_data/uniprot/uniprot_sprot_human.dat.gz
      type: translates to
      label: translates_to

  outdir: uniprot
  nodes: False
  edges: True

uniprotkb_sprot_translates_of:
  adapter:
    module: biocypher_metta.adapters.hsa.uniprot_adapter
    cls: UniprotAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/uniprot/uniprot_sprot_invertebrates_DMEL.dat.gz
      hsa_filepath: /mnt/hdd_2/abdu/biocypher_data/uniprot/uniprot_sprot_human.dat.gz
      type: translation of
      label: translation_of

  outdir: uniprot
  nodes: False
  edges: True

pathway:
  adapter:
    module: biocypher_metta.adapters.hsa.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactomePathways.txt
      pubmed_map_path: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactionPMIDS.txt

  outdir: reactome
  nodes: True
  edges: False

genes_pathways:
  adapter:
    module: biocypher_metta.adapters.hsa.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/Ensembl2Reactome_All_Levels.txt
      label: genes_pathways

  outdir: reactome
  nodes: False
  edges: True

parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.hsa.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactomePathwaysRelation.txt
      label: parent_pathway_of

  outdir: reactome
  nodes: False
  edges: True

child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.hsa.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactomePathwaysRelation.txt
      label: child_pathway_of

  outdir: reactome
  nodes: False
  edges: True

tflink:
    adapter:
        module: biocypher_metta.adapters.hsa.tflink_adapter
        cls: TFLinkAdapter
        args:
          dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/tflink/TFLink_Drosophila_melanogaster_interactions_All_simpleFormat_v1.0.tsv.gz
          dmel_entrez_to_ensemble_map: ./aux_files/dmel_entrez_to_ensembl.pkl
          hsa_filepath: /mnt/hdd_2/abdu/biocypher_data/tflink/tflink_homo_sapiens_interactions.tsv.gz
          hsa_entrez_to_ensemble_map: ./aux_files/hsa_entrez_to_ensembl.pkl

    outdir: tflink
    nodes: False
    edges: True

string:
  adapter:
    module: biocypher_metta.adapters.hsa.string_ppi_adapter
    cls: StringPPIAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/string/7227.protein.links.v12.0.txt.gz
      dmel_ensembl_to_uniprot_map: ./aux_files/hsa_string_ensembl_uniprot_map.pkl
      hsa_filepath: /mnt/hdd_2/abdu/biocypher_data/string/string_human_ppi_v12.0.txt.gz
      hsa_ensembl_to_uniprot_map: ./aux_files/hsa_string_ensembl_uniprot_map.pkl

  outdir: string
  nodes: False
  edges: True

