
dmel_gene_group:
  adapter:
    module: biocypher_metta.adapters.dmel.gene_group_adapter
    cls: GeneGroupAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gene_group_data_fb_2024_04.tsv.gz
       dmel_groups_hgnc_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gene_groups_HGNC_fb_2024_04.tsv.gz
  outdir: flybase/gene_groups
  nodes: True
  edges: False


dmel_pathway_gene_group:
  adapter:
    module: biocypher_metta.adapters.dmel.pathway_gene_group_adapter
    cls: PathwayGeneGroupAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/pathway_group_data_fb_2024_04.tsv.gz
       dmel_groups_hgnc_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gene_groups_HGNC_fb_2024_04.tsv.gz
  outdir: flybase/pathway_gene_groups
  nodes: True
  edges: False


dmel_disease_model:
  adapter:
    module: biocypher_metta.adapters.dmel.disease_model_adapter
    cls: DiseaseModelAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/disease_model_annotations_fb_2024_04.tsv.gz
  outdir: flybase/disease_model
  nodes: True
  edges: False


dmel_genotype_phenotype:
  adapter:
    module: biocypher_metta.adapters.dmel.genotype_phenotype_adapter
    cls: GenotypePhenotypeAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/genotype_phenotype_data_fb_2024_04.tsv.gz
  outdir: flybase/genotype_phenotype
  nodes: True
  edges: False

gaf:
  adapter:
    module: biocypher_metta.adapters.hsa.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gene_association.fb.gz
      gaf_type: 'dmel'
      label: go_gene

  outdir: gaf
  nodes: False
  edges: True


go_ontology_terms:
  adapter:
    module: biocypher_metta.adapters.gene_ontology_adapter
    cls: GeneOntologyAdapter
    args:
      ontology: 'go'
      type: node
      dry_run: False

  outdir: gene_ontology
  nodes: True
  edges: False


go_subclass_of:
  adapter:
    module: biocypher_metta.adapters.gene_ontology_adapter
    cls: GeneOntologyAdapter
    args:
      ontology: 'go'
      label: go_subclass_of
      type: edge
      dry_run: True

  outdir: gene_onotology
  nodes: False
  edges: True

sequence_ontology:
  adapter:
    module: biocypher_metta.adapters.sequence_ontology_adapter
    cls: SequenceOntologyAdapter
    args:
      ontology: 'so'
      type: node
      dry_run: False
      add_description: False
      cache_dir: ./ontology_dataset_cache
  outdir: flybase_ontologies
  nodes: True
  edges: False

so_sequence_subclass_of:
  adapter:
    module: biocypher_metta.adapters.sequence_ontology_adapter
    cls: SequenceOntologyAdapter
    args:
      ontology: 'so'
      label: so_subclass_of
      type: edge
      dry_run: False
  7    cache_dir: ./ontology_dataset_cache
  outdir: flybase_ontologies
  nodes: False
  edges: True


dmel_gene_to_sequence_ontology:
  adapter:
    module: biocypher_metta.adapters.gene_so_adapter
    cls: GeneToSequenceOntologyAdapter
    args:
       filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/dmel_gene_sequence_ontology_annotations_fb_2024_05.tsv.gz
  outdir: gene_so
  nodes: False
  edges: True

FB_development_ontology:
  adapter:
    module: biocypher_metta.adapters.dmel.FBdevelopment_ontology_adapter
    cls: FBDevelopmentOntologyAdapter
    args:
      ontology: 'FBdv'
      type: node
      dry_run: False
      add_description: False
      cache_dir: ./ontology_dataset_cache
  outdir: flybase_ontologies
  nodes: True
  edges: False

FBdv_subclass_of:
  adapter:
    module: biocypher_metta.adapters.dmel.FBdevelopment_ontology_adapter
    cls: FBDevelopmentOntologyAdapter
    args:
      ontology: 'FBdv'
      label: FBdv_subclass_of
      type: edge
      dry_run: False
      cache_dir: ./ontology_dataset_cache
  outdir: flybase_ontologies
  nodes: False
  edges: True


molecular_interactions_ontology:
  adapter:
    module: biocypher_metta.adapters.molecular_interactions_ontology_adapter
    cls: MolecularInteractionsOntologyAdapter
    args:
      ontology: 'mi'
      type: node
      dry_run: False
      add_description: False
      cache_dir: ./ontology_dataset_cache
  outdir: flybase_ontologies
  nodes: True
  edges: False

molecular_interactions_subclass_of:
  adapter:
    module: biocypher_metta.adapters.molecular_interactions_ontology_adapter
    cls: MolecularInteractionsOntologyAdapter
    args:
      ontology: 'mi'
      label: mi_subclass_of
      type: edge
      dry_run: False
      cache_dir: ./ontology_dataset_cache
  outdir: flybase_ontologies
  nodes: False
  edges: True


disease_ontology:
  adapter:
    module: biocypher_metta.adapters.disease_ontology_adapter
    cls: DiseaseOntologyAdapter
    args:
      ontology: 'do'
      type: node
      dry_run: False
      add_description: False
      cache_dir: ./ontology_dataset_cache
  outdir: flybase_ontologies
  nodes: True
  edges: False

disease_do_subclass_of:
  adapter:
    module: biocypher_metta.adapters.disease_ontology_adapter
    cls: DiseaseOntologyAdapter
    args:
      ontology: 'do'
      label: do_subclass_of
      type: edge
      dry_run: False
      cache_dir: ./ontology_dataset_cache
  outdir: flybase_ontologies
  nodes: False
  edges: True


orthology_adapter:
    adapter:
        module: biocypher_metta.adapters.orthology_adapter
        cls: OrthologyAssociationAdapter
        args:
          dmel_data_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/dmel_human_orthologs_disease_fb_2024_04.tsv.gz
          hsa_hgnc_to_ensemble_map: ./aux_files/hgnc_ensembl_map.pkl
    outdir: orthologs
    nodes: False
    edges: True


paralogy_adapter:
    adapter:
        module: biocypher_metta.adapters.paralogy_adapter
        cls: ParalogyAssociationAdapter
        args:
          dmel_data_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/dmel_paralogs_fb_2024_04.tsv.gz
    outdir: paralogs
    nodes: False
    edges: True


allele:
  adapter:
    module: biocypher_metta.adapters.allele_adapter
    cls: AlleleAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fbal_to_fbgn_fb_2024_04.tsv.gz
  outdir: allele
  nodes: True
  edges: False

allele:
  adapter:
    module: biocypher_metta.adapters.allele_adapter
    cls: AlleleAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fbal_to_fbgn_fb_2024_04.tsv.gz
       label: allele
  outdir: allele
  nodes: True
  edges: False


dmel_gene_to_allele:
  adapter:
    module: biocypher_metta.adapters.allele_adapter
    cls: AlleleAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fbal_to_fbgn_fb_2024_04.tsv.gz
       label: gene_to_allele
  outdir: allele
  nodes: False
  edges: True

# ptp stands for "protein or transcript to protein"
dmel_ptp_pysical_interaction:
  adapter:
    module: biocypher_metta.adapters.dmel.dmel_physical_interaction_psimi_adapter
    cls: PhysicalInteractionAdapter
    args:
       dmel_filepaths: [
          /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/physical_interactions_mitab_fb_2024_04.tsv.gz,
          /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fbgn_fbtr_fbpp_expanded_fb_2024_05.tsv.gz
       ]
       label: ptp_physically_interacts_with
  outdir: flybase/mi_interactions
  nodes: False
  edges: True

# ptt stands for "protein or transcript to transcript"
dmel_ptt_pysical_interaction:
  adapter:
    module: biocypher_metta.adapters.dmel.dmel_physical_interaction_psimi_adapter
    cls: PhysicalInteractionAdapter
    args:
       dmel_filepaths: [
          /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/physical_interactions_mitab_fb_2024_04.tsv.gz,
          /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fbgn_fbtr_fbpp_expanded_fb_2024_05.tsv.gz
       ]
       label: ptt_physically_interacts_with
  outdir: flybase/mi_interactions
  nodes: False
  edges: True


dmel_gene_genetic_adapter:
    adapter:
        module: biocypher_metta.adapters.dmel.gene_genetic_association_adapter
        cls: GeneGeneticAssociationAdapter
        args:
          dmel_data_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gene_genetic_interactions_fb_2024_04.tsv.gz
    outdir: flybase/gene_genetic
    nodes: False
    edges: True


dmel_allele_genetic_interaction_adapter:
    adapter:
        module: biocypher_metta.adapters.dmel.allele_genetic_interaction_adapter
        cls: AlleleGeneticInteractionAdapter
        args:
          dmel_data_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/allele_genetic_interactions_fb_2024_04.tsv.gz
    outdir: flybase/allele_genetic
    nodes: True
    edges: False


gencode_gene:
  adapter:
    module: biocypher_metta.adapters.gencode_gene_adapter
    cls: GencodeGeneAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/Drosophila_melanogaster.BDGP6.46.59.gtf.gz
      dmel_gene_alias_file_path: ./aux_files/Drosophila_melanogaster.gene_info.gz
      dmel_summaries_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/best_gene_summary_fb_2024_04.tsv.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gencode.annotation.gtf.gz
      hsa_gene_alias_file_path: ./aux_files/Homo_sapiens.gene_info.gz

  outdir: gencode/gene
  nodes: True
  edges: False


gencode_transcripts:
  adapter:
    module: biocypher_metta.adapters.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gencode.annotation.gtf.gz
      type: transcript
      label: transcript

  outdir: gencode/transcript
  nodes: True
  edges: False


gencode_exon:
  adapter:
    module: biocypher_metta.adapters.gencode_exon_adapter
    cls: GencodeExonAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gencode.annotation.gtf.gz

  outdir: gencode/exon
  nodes: True
  edges: False

transcribed_to:
  adapter:
    module: biocypher_metta.adapters.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gencode.annotation.gtf.gz
      type: transcribed to
      label: transcribed_to

  outdir: gencode
  nodes: False
  edges: True

transcribed_from:
  adapter:
    module: biocypher_metta.adapters.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gencode.annotation.gtf.gz
      type: transcribed from
      label: transcribed_from

  outdir: gencode
  nodes: False
  edges: True


RNASeq_library:
  adapter:
    module: biocypher_metta.adapters.RNASeq_library_adapter
    cls: RnaseqLibraryAdapter
    args:
      dmel_data_filepaths: [
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/scRNA-Seq_gene_expression_fb_2024_04.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/high-throughput_gene_expression_fb_2024_04.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gene_rpkm_report_fb_2024_04.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fca2_fbgn_gene_output.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fca2_fbgn_transcriptGene_output.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fca2_fbgn_mir_gene_output.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fca2_fbgn_mir_transcript_output.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/afca_afca_annotation_group_by_mean.tsv.gz,
      ]
      hsa_filepaths: [

      ]
      #type: scRNASeq library
      #label: scrnaseq_library

  outdir: rnaseq
  nodes: True
  edges: False


expression_value:
  adapter:
    module: biocypher_metta.adapters.expression_value_adapter
    cls: ExpressionValueAdapter
    args:
      dmel_data_filepaths: [
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/scRNA-Seq_gene_expression_fb_2024_04.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/high-throughput_gene_expression_fb_2024_04.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/gene_rpkm_report_fb_2024_04.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fca2_fbgn_gene_output.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fca2_fbgn_transcriptGene_output.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fca2_fbgn_mir_gene_output.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/fca2_fbgn_mir_transcript_output.tsv.gz,
                             /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/afca_afca_annotation_group_by_mean.tsv.gz,
      ]      
      #hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/uniprot/uniprot_sprot_human.dat.gz
      #type: expression value
      #label: expression_value

  outdir: rnaseq
  nodes: False
  edges: True


uniprotkb_sprot:
  adapter:
    module: biocypher_metta.adapters.uniprot_protein_adapter
    cls: UniprotProteinAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/uniprot_sprot_invertebrates_DMEL.dat.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/uniprot_sprot_human.dat.gz
  outdir: uniprot
  nodes: True
  edges: False


uniprotkb_sprot_translates_to:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/uniprot_sprot_invertebrates_DMEL.dat.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/uniprot_sprot_human.dat.gz
      type: translates to
      label: translates_to

  outdir: uniprot
  nodes: False
  edges: True

uniprotkb_sprot_translates_of:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/uniprot_sprot_invertebrates_DMEL.dat.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/uniprot_sprot_human.dat.gz
      type: translation of
      label: translation_of

  outdir: uniprot
  nodes: False
  edges: True

pathway:
  adapter:
    module: biocypher_metta.adapters.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/ReactomePathways.txt
      pubmed_map_path: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/ReactionPMIDS.txt

  outdir: reactome
  nodes: True
  edges: False

genes_pathways:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/Ensembl2Reactome_All_Levels.txt
      label: genes_pathways

  outdir: reactome
  nodes: False
  edges: True

parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/ReactomePathwaysRelation.txt
      label: parent_pathway_of

  outdir: reactome
  nodes: False
  edges: True

child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/ReactomePathwaysRelation.txt
      label: child_pathway_of

  outdir: reactome
  nodes: False
  edges: True


tflink:
    adapter:
        module: biocypher_metta.adapters.tflink_adapter
        cls: TFLinkAdapter
        args:
          dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/TFLink_Drosophila_melanogaster_interactions_All_simpleFormat_v1.0.tsv.gz
          dmel_entrez_to_ensemble_map: ./aux_files/dmel_entrez_to_ensembl.pkl
          hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/tflink_homo_sapiens_interactions.tsv.gz
          hsa_entrez_to_ensemble_map: ./aux_files/hsa_entrez_to_ensembl.pkl

    outdir: tflink
    nodes: False
    edges: True

string:
  adapter:
    module: biocypher_metta.adapters.string_ppi_adapter
    cls: StringPPIAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/7227.protein.links.v12.0.txt.gz
      dmel_ensembl_to_uniprot_map: ./aux_files/dmel_string_ensembl_uniprot_map.pkl
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act_sources/string_human_ppi_v12.0.txt.gz
      hsa_ensembl_to_uniprot_map: ./aux_files/hsa_string_ensembl_uniprot_map.pkl

  outdir: string
  nodes: False
  edges: True

