
dmel_gene_group:
  adapter:
    module: biocypher_metta.adapters.dmel.gene_group_adapter
    cls: GeneGroupAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/gene_group_data_fb_2024_03.tsv.gz
       dmel_groups_hgnc_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/gene_groups_HGNC_fb_2024_03.tsv.gz
  outdir: flybase/gene_groups
  nodes: True
  edges: False


dmel_pathway_gene_group:
  adapter:
    module: biocypher_metta.adapters.dmel.pathway_gene_group_adapter
    cls: PathwayGeneGroupAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/pathway_group_data_fb_2024_03.tsv.gz
       dmel_groups_hgnc_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/gene_groups_HGNC_fb_2024_03.tsv.gz
  outdir: flybase/pathway_gene_groups
  nodes: True
  edges: False


dmel_disease_model:
  adapter:
    module: biocypher_metta.adapters.dmel.disease_model_adapter
    cls: DiseaseModelAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/disease_model_annotations_fb_2024_03.tsv.gz
  outdir: flybase/disease_model
  nodes: True
  edges: False


dmel_genotype_phenotype:
  adapter:
    module: biocypher_metta.adapters.dmel.genotype_phenotype_adapter
    cls: GenotypePhenotypeAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/genotype_phenotype_data_fb_2024_03.tsv.gz
  outdir: flybase/genotype_phenotype
  nodes: True
  edges: False


orthology_adapter:
    adapter:
        module: biocypher_metta.adapters.orthology_adapter
        cls: OrthologyAssociationAdapter
        args:
          dmel_data_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/dmel_human_orthologs_disease_fb_2024_03.tsv.gz
          hsa_hgnc_to_ensemble_map: ./aux_files/hgnc_ensembl_map.pkl
    outdir: orthologs
    nodes: False
    edges: True


paralogy_adapter:
    adapter:
        module: biocypher_metta.adapters.paralogy_adapter
        cls: ParalogyAssociationAdapter
        args:
          dmel_data_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/dmel_paralogs_fb_2024_03.tsv.gz
    outdir: paralogs
    nodes: False
    edges: True


allele:
  adapter:
    module: biocypher_metta.adapters.allele_adapter
    cls: AlleleAdapter
    args:
       dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/fbal_to_fbgn_fb_2024_03.tsv.gz
  outdir: allele
  nodes: True
  edges: False


dmel_gene_genetic_adapter:
    adapter:
        module: biocypher_metta.adapters.dmel.gene_genetic_association_adapter
        cls: GeneGeneticAssociationAdapter
        args:
          dmel_data_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/gene_genetic_interactions_fb_2024_03.tsv.gz
    outdir: flybase/gene_genetic
    nodes: False
    edges: True

dmel_allele_genetic_interaction_adapter:
    adapter:
        module: biocypher_metta.adapters.dmel.allele_genetic_interaction_adapter
        cls: AlleleGeneticInteractionAdapter
        args:
          dmel_data_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/allele_genetic_interactions_fb_2024_03.tsv.gz
    outdir: flybase/allele_genetic
    nodes: True
    edges: False


gencode_gene:
  adapter:
    module: biocypher_metta.adapters.gencode_gene_adapter
    cls: GencodeGeneAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/Drosophila_melanogaster.BDGP6.46.59.gtf.gz
      dmel_gene_alias_file_path: ./aux_files/Drosophila_melanogaster.gene_info.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/gencode.annotation.gtf.gz
      hsa_gene_alias_file_path: ./aux_files/Homo_sapiens.gene_info.gz

  outdir: gencode/gene
  nodes: True
  edges: False


gencode_transcripts:
  adapter:
    module: biocypher_metta.adapters.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/gencode.annotation.gtf.gz
      type: transcript
      label: transcript

  outdir: gencode/transcript
  nodes: True
  edges: False


gencode_exon:
  adapter:
    module: biocypher_metta.adapters.gencode_exon_adapter
    cls: GencodeExonAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/gencode.annotation.gtf.gz

  outdir: gencode/exon
  nodes: True
  edges: False

transcribed_to:
  adapter:
    module: biocypher_metta.adapters.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/gencode.annotation.gtf.gz
      type: transcribed to
      label: transcribed_to

  outdir: gencode
  nodes: False
  edges: True

transcribed_from:
  adapter:
    module: biocypher_metta.adapters.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/gencode.annotation.gtf.gz
      type: transcribed from
      label: transcribed_from

  outdir: gencode
  nodes: False
  edges: True


uniprotkb_sprot:
  adapter:
    module: biocypher_metta.adapters.uniprot_protein_adapter
    cls: UniprotProteinAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/uniprot_sprot_invertebrates_DMEL.dat.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/uniprot_sprot_human.dat.gz
  outdir: uniprot
  nodes: True
  edges: False

uniprotkb_sprot_translates_to:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/uniprot_sprot_invertebrates_DMEL.dat.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/uniprot_sprot_human.dat.gz
      type: translates to
      label: translates_to

  outdir: uniprot
  nodes: False
  edges: True

uniprotkb_sprot_translates_of:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/uniprot_sprot_invertebrates_DMEL.dat.gz
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/uniprot_sprot_human.dat.gz
      type: translation of
      label: translation_of

  outdir: uniprot
  nodes: False
  edges: True

pathway:
  adapter:
    module: biocypher_metta.adapters.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/ReactomePathways.txt
      pubmed_map_path: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/ReactionPMIDS.txt

  outdir: reactome
  nodes: True
  edges: False

genes_pathways:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/Ensembl2Reactome_All_Levels.txt
      label: genes_pathways

  outdir: reactome
  nodes: False
  edges: True

parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/ReactomePathwaysRelation.txt
      label: parent_pathway_of

  outdir: reactome
  nodes: False
  edges: True

child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/ReactomePathwaysRelation.txt
      label: child_pathway_of

  outdir: reactome
  nodes: False
  edges: True


tflink:
    adapter:
        module: biocypher_metta.adapters.tflink_adapter
        cls: TFLinkAdapter
        args:
          dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/TFLink_Drosophila_melanogaster_interactions_All_simpleFormat_v1.0.tsv.gz
          dmel_entrez_to_ensemble_map: ./aux_files/dmel_entrez_to_ensembl.pkl
          hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/tflink_homo_sapiens_interactions.tsv.gz
          hsa_entrez_to_ensemble_map: ./aux_files/hsa_entrez_to_ensembl.pkl

    outdir: tflink
    nodes: False
    edges: True

string:
  adapter:
    module: biocypher_metta.adapters.string_ppi_adapter
    cls: StringPPIAdapter
    args:
      dmel_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/7227.protein.links.v12.0.txt.gz
      dmel_ensembl_to_uniprot_map: ./aux_files/dmel_string_ensembl_uniprot_map.pkl
      hsa_filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/net_act/string_human_ppi_v12.0.txt.gz
      hsa_ensembl_to_uniprot_map: ./aux_files/hsa_string_ensembl_uniprot_map.pkl

  outdir: string
  nodes: False
  edges: True

